import re
from dataclasses import dataclass, field
from typing import ClassVar

@dataclass
class UriShortener:
    """
    Maps long URIs to short numeric codes and back to save tokens and prevent LLM hallucinations.
    
    Format:
    - Base URLs get an ID: =1, =2
    - Fragments get a sub-ID: =1#1, =1#2
    
    EXTENSIBILITY NOTE:
    This core implementation handles standard encoding/decoding and basic hallucination detection. 
    In production environments, LLMs might invent new formatting errors (e.g., swapping labels 
    and codes, or dropping brackets). You can extend this class with custom regex normalizers 
    before calling `decode_text()` to fit your specific domain requirements.
    """

    base_to_id: dict[str, int] = field(default_factory=dict)
    suffix_maps: dict[str, dict[str, int]] = field(default_factory=dict)
    full_to_short: dict[str, str] = field(default_factory=dict)
    short_to_full: dict[str, str] = field(default_factory=dict)

    # Regex for inline Markdown links: [label](uri)
    link_pattern: ClassVar[re.Pattern] = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
    # Strict pattern for valid short codes: =digits or =digits#fragment
    short_code_pattern: ClassVar[re.Pattern] = re.compile(r"^=\d+(?:#[\w.~-]+)?$")

    def _encode_single_uri(self, uri: str) -> str:
        """Convert a single full URI to a short code like '=1' or '=2#1'."""
        if self.short_code_pattern.match(uri) or uri in self.full_to_short:
            return self.full_to_short.get(uri, uri)

        # Split on the first '#'
        hash_index = uri.find("#")
        if hash_index == -1:
            base, suffix = uri, None
        else:
            base = uri[:hash_index]
            suffix = uri[hash_index + 1 :] 

        # Assign base ID
        if base not in self.base_to_id:
            self.base_to_id[base] = len(self.base_to_id) + 1
        base_id = self.base_to_id[base]

        # Assign fragment sub-ID
        if not suffix:
            short = f"={base_id}"
        else:
            suffix_map = self.suffix_maps.setdefault(base, {})
            if suffix not in suffix_map:
                suffix_map[suffix] = len(suffix_map) + 1
            short = f"={base_id}#{suffix_map[suffix]}"

        # Store bidirectional mapping
        self.full_to_short[uri] = short
        self.short_to_full[short] = uri

        return short

    def encode_text(self, text: str) -> str:
        """Convert all URIs in Markdown links inside 'text' to numeric codes."""
        def repl(match: re.Match) -> str:
            label, uri = match.group(1), match.group(2)
            short = self._encode_single_uri(uri)
            return f"[{label}]({short})"

        return self.link_pattern.sub(repl, text)

    def decode_text(self, text: str) -> str:
        """Convert short codes in Markdown links back to the original URIs."""
        # Reverse lookup for base IDs to handle hallucinated fragments gracefully
        id_to_base = {v: k for k, v in self.base_to_id.items()}

        def repl(match: re.Match) -> str:
            label, uri = match.group(1), match.group(2)

            # 1. Exact match (Normal case)
            if uri in self.short_to_full:
                return f"[{label}]({self.short_to_full[uri]})"

            # 2. Fallback: Base is correct, but LLM hallucinated the fragment
            if uri.startswith("=") and self.short_code_pattern.match(uri):
                uri_without_prefix = uri[1:]
                hash_idx = uri_without_prefix.find("#")
                base_str = uri_without_prefix[:hash_idx] if hash_idx != -1 else uri_without_prefix
                
                try:
                    base_id = int(base_str)
                    if base_id in id_to_base:
                        # Restore base URI, ignore hallucinated fragment
                        return f"[{label}]({id_to_base[base_id]})"
                except ValueError:
                    pass

            # 3. Unrecognized or not a short code, leave unchanged
            return match.group(0)

        return self.link_pattern.sub(repl, text)

    def find_hallucinated_codes(self, text: str) -> set[str]:
        """Find short codes generated by the LLM that were never encoded."""
        hallucinated = set()
        for match in self.link_pattern.finditer(text):
            uri = match.group(2)
            if uri.startswith("=") and uri not in self.short_to_full:
                hallucinated.add(uri)
        return hallucinated